version: '{build}'
shallow_clone: true
clone_depth: 1
init:
- git config --global core.autocrlf input

environment:
  matrix:
    - QT5: C:\Qt\5.8\msvc2015_64
      PLATFORM: X64
      SPEC: win32-msvc2015
      VSVER: 14



before_build:
  - set PATH=%QT5%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - dir C:\Qt\5.8\msvc2015_64
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS")) 
  - if "%PLATFORM%" == "X86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%PLATFORM%" == "X64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%PLATFORM%" == "X64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - qmake -spec %SPEC% -r CONFIG+=debug_and_release untitled.pro

build_script:
  - jom
  
after_build:
  - echo "%DEPLOY_DIR%"
